require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TicketUpdatesController do

  # This should return the minimal set of attributes required to create a valid
  # TicketUpdate. As you add validations to TicketUpdate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TicketUpdatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ticket_updates as @ticket_updates" do
      ticket_update = TicketUpdate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ticket_updates).should eq([ticket_update])
    end
  end

  describe "GET show" do
    it "assigns the requested ticket_update as @ticket_update" do
      ticket_update = TicketUpdate.create! valid_attributes
      get :show, {:id => ticket_update.to_param}, valid_session
      assigns(:ticket_update).should eq(ticket_update)
    end
  end

  describe "GET new" do
    it "assigns a new ticket_update as @ticket_update" do
      get :new, {}, valid_session
      assigns(:ticket_update).should be_a_new(TicketUpdate)
    end
  end

  describe "GET edit" do
    it "assigns the requested ticket_update as @ticket_update" do
      ticket_update = TicketUpdate.create! valid_attributes
      get :edit, {:id => ticket_update.to_param}, valid_session
      assigns(:ticket_update).should eq(ticket_update)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TicketUpdate" do
        expect {
          post :create, {:ticket_update => valid_attributes}, valid_session
        }.to change(TicketUpdate, :count).by(1)
      end

      it "assigns a newly created ticket_update as @ticket_update" do
        post :create, {:ticket_update => valid_attributes}, valid_session
        assigns(:ticket_update).should be_a(TicketUpdate)
        assigns(:ticket_update).should be_persisted
      end

      it "redirects to the created ticket_update" do
        post :create, {:ticket_update => valid_attributes}, valid_session
        response.should redirect_to(TicketUpdate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ticket_update as @ticket_update" do
        # Trigger the behavior that occurs when invalid params are submitted
        TicketUpdate.any_instance.stub(:save).and_return(false)
        post :create, {:ticket_update => {}}, valid_session
        assigns(:ticket_update).should be_a_new(TicketUpdate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TicketUpdate.any_instance.stub(:save).and_return(false)
        post :create, {:ticket_update => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ticket_update" do
        ticket_update = TicketUpdate.create! valid_attributes
        # Assuming there are no other ticket_updates in the database, this
        # specifies that the TicketUpdate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TicketUpdate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ticket_update.to_param, :ticket_update => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ticket_update as @ticket_update" do
        ticket_update = TicketUpdate.create! valid_attributes
        put :update, {:id => ticket_update.to_param, :ticket_update => valid_attributes}, valid_session
        assigns(:ticket_update).should eq(ticket_update)
      end

      it "redirects to the ticket_update" do
        ticket_update = TicketUpdate.create! valid_attributes
        put :update, {:id => ticket_update.to_param, :ticket_update => valid_attributes}, valid_session
        response.should redirect_to(ticket_update)
      end
    end

    describe "with invalid params" do
      it "assigns the ticket_update as @ticket_update" do
        ticket_update = TicketUpdate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TicketUpdate.any_instance.stub(:save).and_return(false)
        put :update, {:id => ticket_update.to_param, :ticket_update => {}}, valid_session
        assigns(:ticket_update).should eq(ticket_update)
      end

      it "re-renders the 'edit' template" do
        ticket_update = TicketUpdate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TicketUpdate.any_instance.stub(:save).and_return(false)
        put :update, {:id => ticket_update.to_param, :ticket_update => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ticket_update" do
      ticket_update = TicketUpdate.create! valid_attributes
      expect {
        delete :destroy, {:id => ticket_update.to_param}, valid_session
      }.to change(TicketUpdate, :count).by(-1)
    end

    it "redirects to the ticket_updates list" do
      ticket_update = TicketUpdate.create! valid_attributes
      delete :destroy, {:id => ticket_update.to_param}, valid_session
      response.should redirect_to(ticket_updates_url)
    end
  end

end
